# **Pandas**
---
 **Pandas** is a data manipulation and analysis library for Python.
# Key Features:
*   Introduces two primary data structures: Series (1D) and DataFrame (2D).
*   Facilitates data cleaning, exploration, and manipulation.
*   Enables working with labeled and structured data efficiently.

---



All ***pandas*** feature under same platform:

collect all data that can be collected through pandas libary of the link of **Titanic passenger details** as
https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

# ***Questions:***

---




1.  Importing data set and read csv files i.e:  https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
            using: data = pd.read_csv("file.csv")
2.  To display all information about data and column names with data-type,
            using: data.info()
3.  To get all static value int data of data ,
            using: data.describe()
4.  To check whether a value is null or not,
            using: data.isnull()
5.  To fill all null (NAN) value with 1 and inplace for storing it permenant
            using: data.fillna(1,inplace=True)
6.  After the change to check whether null value exist or not to each column
            using: data.isnull()
7.  To set index as Passenger Id column
            using: data.set_index("Passenger_id")
8.  to gain matric count value(row,column)
            using: data.shape()
9.  To add new column of name Years at index 5
            using: data.insert(loc=5, column='Years', value=2000)
10. to drop column
            using: data.drop("column_name",axis=1,inplace=True)
11. to display data
            using: data
12. To set index as Passenger Id column as perment
            using: data.set_index("Passenger_id",inplace=True)
13. To select particular column from data
            using: data[['c_name', 'c_name']]
14. To count unique value
            using: data["c_name"].value_counts()
15. To count value that meets condition i.e ['Age']<=30
            using: len(data[data["c_name"] <=int)
16. To display all value that meets condition
            using: data[data["c_name"] <=int
17. To count value that meets condition i.e ['Age']<=30 and ['Age']<=40
            using: len(data[(data['Age']>=30) & (data['Age']<=40) ])
18. To display top 5 data
            using: data.head(5)
19. To count number of male and female from Sex column of data
            using: data['Sex'].value_counts()
20. To count number of '0' and '1'from survived column of data
            using:data['survived'].value_counts()